services:
  streamlit:
    build: .
    container_name: workers-streamlit
    ports:
      - "8000:8501"
    volumes:
      - .:/app
    command: streamlit run app/app.py --server.address=0.0.0.0

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////app/src/mlflow.db